
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: vault-controller-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - vault.redoute.io
  resources:
  - policies
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.redoute.io
  resources:
  - policies/status
  - role/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vault.redoute.io
  resources:
  - sysauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vault.redoute.io
  resources:
  - sysauths/status
  verbs:
  - get
  - patch
  - update
