# permissions for end users to view sysauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sysauth-viewer-role
rules:
- apiGroups:
  - vault.redoute.io
  resources:
  - sysauths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vault.redoute.io
  resources:
  - sysauths/status
  verbs:
  - get
