apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-controller
  namespace: vault-controller-system
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
  name: vault-controller
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1000
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1000
    rule: MustRunAs
  volumes:
  - secret
  - emptyDir
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-controller
  namespace: vault-controller-system
rules:
- apiGroups:
  - extensions
  resourceNames:
  - vault-controller
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-controller
  namespace: vault-controller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-controller
subjects:
- kind: ServiceAccount
  name: vault-controller
  namespace: vault-controller-system
